INSERT INTO tools (name) VALUES ('navigator''s tools');
INSERT INTO tools (name) VALUES ('cartographer''s tools');
INSERT INTO tools (name) VALUES ('herbalism kit');
INSERT INTO tools (name) VALUES ('vehicles (land)');
INSERT INTO tools (name) VALUES ('anyArtisansTool');
INSERT INTO tools (name) VALUES ('gaming set');
INSERT INTO tools (name) VALUES ('anyGamingSet');
INSERT INTO tools (name) VALUES ('disguise kit');
INSERT INTO tools (name) VALUES ('forgery kit');
INSERT INTO tools (name) VALUES ('thieves'' tools');
INSERT INTO tools (name) VALUES ('vehicles (water)');
INSERT INTO tools (name) VALUES ('anyMusicalInstrument');
INSERT INTO tools (name) VALUES ('alchemist''s supplies');
INSERT INTO tools (name) VALUES ('musical instrument');
INSERT INTO tools (name) VALUES ('poisoner''s kit');
INSERT INTO tools (name) VALUES ('tinker''s tools');
INSERT INTO tools (name) VALUES ('brewer''s supplies');
INSERT INTO tools (name) VALUES ('cook''s utensils');
INSERT INTO tools (name) VALUES ('vehicles (air)');
INSERT INTO tools (name) VALUES ('calligrapher''s supplies');
INSERT INTO tools (name) VALUES ('carpenter''s tools');
INSERT INTO tools (name) VALUES ('vehicles (space)');
