-- Inserting Language Scripts
INSERT INTO language_scripts (name) VALUES ('Draconic') ON CONFLICT (name) DO NOTHING;
INSERT INTO language_scripts (name) VALUES ('Dwarvish') ON CONFLICT (name) DO NOTHING;
INSERT INTO language_scripts (name) VALUES ('Elvish') ON CONFLICT (name) DO NOTHING;
INSERT INTO language_scripts (name) VALUES ('Infernal') ON CONFLICT (name) DO NOTHING;
INSERT INTO language_scripts (name) VALUES ('Thorass') ON CONFLICT (name) DO NOTHING;

-- Inserting Languages
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Aarakocra', (SELECT id FROM sources WHERE name = 'MM'), 12, NULL, ARRAY['{@creature aarakocra}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Abanasinian', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Abanasinia'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Abyssal', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter demons|bestiary|source=GGR|tag=demon}', '{@filter devils|bestiary|source=GGR|tag=devil}'], (SELECT id FROM language_scripts WHERE name = 'Infernal'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Abyssal', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['{@filter demons|bestiary|tag=demon}'], (SELECT id FROM language_scripts WHERE name = 'Infernal'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Alzhedo', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Calishite ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Aven', (SELECT id FROM sources WHERE name = 'PSD'), 6, NULL, ARRAY['{@race Aven|PSD}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Blink Dog', (SELECT id FROM sources WHERE name = 'MM'), 318, NULL, ARRAY['{@creature Blink Dog||blink dogs}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Bothii', (SELECT id FROM sources WHERE name = 'SKT'), 86, NULL, ARRAY['{@creature Uthgardt Barbarian Leader|SKT|Uthgardt barbarians}', '{@creature Uthgardt Shaman|SKT|Uthgardt shamans}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Bullywug', (SELECT id FROM sources WHERE name = 'MM'), 35, NULL, ARRAY['{@creature Bullywug||bullywugs}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Celestial', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['{@filter celestials|bestiary|source=ERLW|type=celestial}'], (SELECT id FROM language_scripts WHERE name = 'Celestial'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Celestial', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter angels|bestiary|source=GGR|tag=angel}'], (SELECT id FROM language_scripts WHERE name = 'Celestial'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Celestial', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Gods'], (SELECT id FROM language_scripts WHERE name = 'Celestial'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Celestial', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['{@filter celestials|bestiary|type=celestial}'], (SELECT id FROM language_scripts WHERE name = 'Celestial'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Chessentan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Mulan ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Chondathan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Chondathan ethnic group', 'Tethyrian ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Coalition Pidgin', (SELECT id FROM sources WHERE name = 'PSX'), 6, NULL, ARRAY['Brazen Coalition', '{@race Human (Ixalan)|PSX|Humans}', '{@race Orc (Ixalan)|PSX|Orcs}', '{@race Siren|PSX|Sirens}', '{@race Goblin (Ixalan)|PSX|Goblins}'], NULL, 'The humans of the Brazen Coalition speak a different language—a pidgin of Orc, Siren, and a native human language that is similar to {@language Vampire|PSX} (about as closely related as Italian is to Spanish). Orcs, sirens, and goblins also speak this Brazen Coalition pidgin.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Common', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Trade language of Ansalon'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Common', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['The Five Nations', 'trade language of Khorvaire'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Common', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter humans|bestiary|type=humanoid|tag=any race;human|source=GGR}'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Common', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Humans'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Common', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@filter humans|bestiary|type=humanoid|tag=any race;human}'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Common', (SELECT id FROM sources WHERE name = 'PSI'), 9, NULL, ARRAY['{@race Human (Innistrad)|PSI|Humans}', 'Members of the Church', '{@creature Vampire Neonate|PSI|Vampires}', '{@creature Werewolf (Krallenhorde)|PSI|Werewolves}', '{@creature Geist|PSI|Geists}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Common Trade Pidgin', (SELECT id FROM sources WHERE name = 'PSX'), 6, NULL, ARRAY['Sun Empire', 'River Heralds', 'Legion of Dusk', 'Brazen Coalition', '{@race Human (Ixalan)|PSX|Humans}', '{@race Orc (Ixalan)|PSX|Orcs}', '{@race Siren|PSX|Sirens}', '{@race Goblin (Ixalan)|PSX|Goblins}'], NULL, 'A trade pidgin used in circumstances where members of different peoples do interact with each other. But this language is almost impossible to use for discussions of matters of any depth.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Daelkyr', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['{@filter aberrations|bestiary|type=aberration|source=ERLW}', 'denizens of Khyber'], (SELECT id FROM language_scripts WHERE name = 'Daelkyr'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Damaran', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Damaran ethnic group', 'Nar ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Dethek'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Dambrathan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Arkaiun ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Espruar'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Deep Crow', (SELECT id FROM sources WHERE name = 'AI'), 210, NULL, ARRAY['{@creature Deep Crow|AI|deep crows}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Deep Speech', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['{@creature mind flayer||mind flayers}', '{@creature beholder||beholders}'], (SELECT id FROM language_scripts WHERE name = 'none'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Demonic', (SELECT id FROM sources WHERE name = 'PSI'), 9, NULL, ARRAY['{@filter Demons|bestiary|source=|tag=demon}', '{@filter Devils|bestiary|source=|tag=devil}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Draconic', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Dragons'], (SELECT id FROM language_scripts WHERE name = 'Draconic'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Draconic', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['{@filter dragons|bestiary|source=ERLW|type=dragon}', '{@filter dragonborn|bestiary|type=humanoid|tag=any race;dragonborn|source=ERLW}'], (SELECT id FROM language_scripts WHERE name = 'Draconic'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Draconic', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter dragons|bestiary|source=GGR|type=dragon}'], (SELECT id FROM language_scripts WHERE name = 'Draconic'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Draconic', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Dragons'], (SELECT id FROM language_scripts WHERE name = 'Draconic'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Draconic', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['{@filter dragons|bestiary|type=dragon}', '{@race dragonborn}'], (SELECT id FROM language_scripts WHERE name = 'Draconic'), 'Draconic is thought to be one of the oldest languages and is often used in the study of magic. The language sounds harsh to most other creatures and includes numerous hard consonants and sibilants.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Draconic', (SELECT id FROM sources WHERE name = 'PSI'), 9, NULL, ARRAY['{@filter Dragons|bestiary|source=PSI|type=dragon}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Druidic', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'secret', ARRAY['Selesnya {@class druid||druids}/{@creature druid||druids}', 'Golgari {@class druid||druids}/{@creature druid||druids}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Druidic', (SELECT id FROM sources WHERE name = 'PHB'), 64, 'secret', ARRAY['{@class druid||druids}/{@creature druid||druids}', '{@creature treant||treants}'], NULL, 'Druidic is the secret language of druids. It can be spoken or used to leave hidden messages. Creatures who know this language automatically spot such a message. Others spot the message''s presence with a successful {@dc 15} Wisdom ({@skill Perception}) check but can''t decipher it without magic.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Dwarvish', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Abanasinia', 'Kayolin', 'Thoradin', 'Thorbardin'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Dwarvish', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['Mror Holds'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Dwarvish', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@filter dwarves|bestiary|type=humanoid|tag=any race;dwarf}'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), 'Dwarvish is full of hard consonants and guttural sounds, and those characteristics spill over into whatever other language a dwarf might speak.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Elvish', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Qualinesti', 'Silvanesti', 'Southern Ergoth'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Elvish', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['Aerenal', 'Valenar'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Elvish', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter elves|bestiary|type=humanoid|tag=any race;elf|source=GGR}'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Elvish', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@filter elves|bestiary|type=humanoid|tag=any race;elf}'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), 'Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poems are famous among other races. Many bards learn their language so they can add Elvish ballads to their repertoires.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Ergot', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Northern Ergoth'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Giant', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['Inhabitants of Xen''drik'], (SELECT id FROM language_scripts WHERE name = 'Giant'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Giant', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@creature ogre||ogres}', '{@filter giants|bestiary|type=giant|source=ERLW}'], (SELECT id FROM language_scripts WHERE name = 'Minotaur'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Giant', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Cyclopes, giants'], (SELECT id FROM language_scripts WHERE name = 'Minotaur'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Giant', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@creature ogre||ogres}', '{@filter giants|bestiary|type=giant}'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Giant Eagle', (SELECT id FROM sources WHERE name = 'MM'), 324, NULL, ARRAY['{@creature Giant Eagle||giant eagles}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Giant Elk', (SELECT id FROM sources WHERE name = 'MM'), 325, NULL, ARRAY['{@creature Giant Elk||giant elks}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Giant Owl', (SELECT id FROM sources WHERE name = 'MM'), 327, NULL, ARRAY['{@creature Giant Owl||giant owls}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Gith', (SELECT id FROM sources WHERE name = 'MM'), 160, NULL, ARRAY['{@creature Githzerai Monk||githzerai monks}', '{@creature Githyanki Warrior||githyanki warriors}', '{@creature Githzerai Zerth||githzerai zerths}', '{@creature Githyanki Knight||githyanki knights}'], (SELECT id FROM language_scripts WHERE name = 'Tir''su'), 'The Gith Alphabet
The gith use a written language composed of alphabetic symbols arranged in circular clusters called tir''su. Each "spoke" on the wheel corresponds to a letter of the alphabet. Each cluster of characters represents a single word, and multiple tir''su connect to form phrases and sentences.
Githyanki and githzerai both speak Gith, but each race has a distinct dialect and accent. Similarly, the two races of gith differentiate their language by how they write it. Githyanki write a tir''su clockwise, starting at the top. Githzerai use the same letter symbols but write their tir''su counterclockwise, starting from the bottom.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Gnoll', (SELECT id FROM sources WHERE name = 'MM'), 163, NULL, ARRAY['{@creature Gnoll||gnolls}', '{@creature Gnoll Pack Lord||gnoll pack lords}', '{@creature Gnoll Fang of Yeenoghu||gnoll fangs of Yeenoghu}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Gnomish', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Sancrist'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Gnomish', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['Zilargo'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Gnomish', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@filter gnomes|bestiary|type=humanoid|tag=any race;gnome}'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), 'The Gnomish language, which uses the Dwarvish script, is renowned for its technical treatises and its catalogs of knowledge about the natural world.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Goblin', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Taman Busuk'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Goblin', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['Darguun', 'Droaam', 'Shadow Marches', 'monsters of Khorvaire'], (SELECT id FROM language_scripts WHERE name = 'Goblin'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Goblin', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter goblins|bestiary|tag=any race|source=GGR}'], (SELECT id FROM language_scripts WHERE name = 'Common'), 'In Ravnica, Goblin is a simplistic language with a limited vocabulary and fluid rules of grammar, unsuited for any sophisticated conversation.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Goblin', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@filter goblinoids|bestiary|tag=goblinoid}'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Grell', (SELECT id FROM sources WHERE name = 'MM'), 172, NULL, ARRAY['{@creature Grell||grells}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Grung', (SELECT id FROM sources WHERE name = 'VGM'), 156, NULL, ARRAY['{@creature Grung|VGM|grungs}', '{@creature Grung Wildling|VGM|grung wildlings}', '{@creature Grung Elite Warrior|VGM|grung elite warriors}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Guran', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Gur ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'A patois of {@language Roushoum|SCAG} and {@language Rashemi|SCAG}.
Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Halfling', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['Talenta Plains'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Halfling', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@filter halflings|bestiary|type=humanoid|tag=any race;halfling}'], (SELECT id FROM language_scripts WHERE name = 'Common'), 'The Halfling language isn''t secret, but halflings are loath to share it with others. They write very little, so they don''t have a rich body of literature. Their oral tradition, however, is very strong. Almost all halflings speak Common to converse with the people in whose lands they dwell or through which they are traveling.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Halruaan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Halruaan ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Draconic'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Homarid', (SELECT id FROM sources WHERE name = 'PSD'), 15, NULL, ARRAY['{@creature Homarid|PSD|homarids}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Hook Horror', (SELECT id FROM sources WHERE name = 'MM'), 189, NULL, ARRAY['{@creature Hook Horror||hook horrors}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Ice Toad', (SELECT id FROM sources WHERE name = 'RoT'), 90, NULL, ARRAY['{@creature Ice Toad|RoT|ice toads}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Illuskan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Illuskan ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Infernal', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['{@filter fiends|bestiary|type=fiend|source=ERLW}'], (SELECT id FROM language_scripts WHERE name = 'Infernal'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Infernal', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['{@filter devils|bestiary|tag=devil}'], (SELECT id FROM language_scripts WHERE name = 'Infernal'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Istarian', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Ancient Istarians'], (SELECT id FROM language_scripts WHERE name = 'Istarian'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Itzocan', (SELECT id FROM sources WHERE name = 'PSX'), 6, NULL, ARRAY['Sun Empire', '{@race Human (Ixalan)|PSX|Humans}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Ixitxachitl', (SELECT id FROM sources WHERE name = 'OotA'), 225, NULL, ARRAY['{@creature ixitxachitl|OotA}', '{@creature Ixitxachitl Cleric|OotA|ixitxachitl clerics}', '{@creature vampiric ixitxachitl|OotA}', '{@creature Vampiric Ixitxachitl Cleric|OotA|vampiric ixitxachitl clerics}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Keldon', (SELECT id FROM sources WHERE name = 'PSD'), 19, NULL, ARRAY['{@race Human (Keldon)|PSD|Keldons}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Kenderspeak', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Goodlund', 'Hylo'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Kharolian', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Plains of Dust', 'Tarsis'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Khenra', (SELECT id FROM sources WHERE name = 'PSA'), 18, NULL, ARRAY['{@race Khenra|PSA}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Khur', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Khur'], (SELECT id FROM language_scripts WHERE name = 'Istarian'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Kothian', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Minotaurs'], (SELECT id FROM language_scripts WHERE name = 'Kothian'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Kraul', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['kraul', '{@creature Kraul Warrior|GGR|kraul warriors}', '{@creature Kraul Death Priest|GGR|kraul death priests}', '{@creature Devkarin Lich|GGR|devkarin liches}'], (SELECT id FROM language_scripts WHERE name = 'Kraul'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Kruthik', (SELECT id FROM sources WHERE name = 'MTF'), 211, NULL, ARRAY['{@creature Young Kruthik|MTF|young kruthiks}', '{@creature Adult Kruthik|MTF|adult kruthiks}', '{@creature Kruthik Hive Lord|MTF|kruthik hive lords}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Leonin', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Leonin'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Loross', (SELECT id FROM sources WHERE name = 'IDRotF'), 221, NULL, NULL, (SELECT id FROM language_scripts WHERE name = 'Draconic'), 'Loross, a language spoken by the Netherese, is a dead tongue. Very few creatures in the world today would recognize it, much less speak it. Loross used the Draconic alphabet in its written form, while the spoken language had many similarities with Elvish, due to the cultural influence the elves had on Netherese civilization. A character who speaks Elvish can understand what a creature speaking Loross is saying, and vice versa. A character who has the Cloistered Scholar or Sage background, or a warlock who knows the Eyes of the Rune Keeper invocation, can translate written Loross without an ability check.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Loxodon', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter loxodons|bestiary|tag=any race|source=GGR}'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Marquesian', (SELECT id FROM sources WHERE name = 'EGW'), 9, NULL, NULL, NULL, 'The Menagerie Coast was settled by colonists from the arid land of Marquet, and their language now holds an unusual position in the Clovis Concord. It is the language of high society, as many Clovis elite are descended from Marquesians, but it is also the language of piracy, since countless lower-class Marquesians defected from the Concord and formed the Revelry pirates.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Merfolk', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@filter merfolk|bestiary|source=GGR|tag=any race;merfolk}'], (SELECT id FROM language_scripts WHERE name = 'Merfolk'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Merfolk', (SELECT id FROM sources WHERE name = 'PSX'), 6, NULL, ARRAY['River Heralds'], (SELECT id FROM language_scripts WHERE name = 'Merfolk'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Midani', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Bedine ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Minotaur', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@race minotaur|ggr|minotaurs}'], (SELECT id FROM language_scripts WHERE name = 'Minotaur'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Minotaur', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Minotaurs'], (SELECT id FROM language_scripts WHERE name = 'Minotaur'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Modron', (SELECT id FROM sources WHERE name = 'MM'), 224, NULL, ARRAY['{@creature Monodrone||monodrones}', '{@creature Duodrone||duodrones}', '{@creature Tridrone||tridrones}', '{@creature Quadrone||quadrones}', '{@creature Pentadrone||pentadrones}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Mulhorandi', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Mulan ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Naga', (SELECT id FROM sources WHERE name = 'PSA'), 18, NULL, ARRAY['{@race Naga|PSA|}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Naush', (SELECT id FROM sources WHERE name = 'EGW'), 9, NULL, NULL, NULL, 'Originally spoken by the Ki''Nau islanders native to the Menagerie Coast, Naush is a thriving language within the multicultural cities of the Clovis Concord. Even sailors who only speak Common incorporate dozens of Naush words into their nautical jargon.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Nerakese', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Neraka'], (SELECT id FROM language_scripts WHERE name = 'Istarian'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Netherese', (SELECT id FROM sources WHERE name = 'HotDQ'), 93, NULL, NULL, (SELECT id FROM language_scripts WHERE name = 'Draconic'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Nordmaarian', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Nordmaar'], (SELECT id FROM language_scripts WHERE name = 'Istarian'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Ogre', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Blode', 'Kern'], (SELECT id FROM language_scripts WHERE name = 'Ogre'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Olman', (SELECT id FROM sources WHERE name = 'TftYP'), 238, NULL, NULL, NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Orc', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['isolated orc tribes'], (SELECT id FROM language_scripts WHERE name = 'Goblin'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Orc', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'standard', ARRAY['{@filter orcs|bestiary|tag=orc}'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), ' Orc is a harsh, grating language with hard consonants. It has no script of its own but is written in the Dwarvish script.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Otyugh', (SELECT id FROM sources WHERE name = 'MM'), 248, NULL, ARRAY['{@creature Otyugh||otyughs}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Primordial', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Elementals'], (SELECT id FROM language_scripts WHERE name = 'Primordial'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Primordial', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['{@filter elementals|bestiary|type=elemental}'], (SELECT id FROM language_scripts WHERE name = 'Primordial'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Primordial', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Tritons'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Primordial', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['{@filter elementals|bestiary|type=elemental}'], (SELECT id FROM language_scripts WHERE name = 'Dwarvish'), 'Primordial is a guttural language, filled with harsh syllables and hard consonants.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Primordial', (SELECT id FROM sources WHERE name = 'PSI'), 9, NULL, ARRAY['Elementals'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Qualith', (SELECT id FROM sources WHERE name = 'VGM'), 75, NULL, ARRAY['{@creature Mind Flayer||Mind Flayers}'], (SELECT id FROM language_scripts WHERE name = 'Qualith'), 'The "writing" of mind flayers, known as Qualith, isn''t as simple as a set of symbols representing sounds or ideas. An inscription in Qualith captures the thoughts of its creator and psionically transmits the thoughts to a mind flayer who later reads the inscription by touching it with its tentacles. Mind flayers write in Qualith by psionically imprinting their messages on nonmagical, nonliving material they grasp or caress with their tentacles. The imprinting causes imperceptible surface changes to the object, and abrasion or degradation of the material can cause the inscription to fade and fail.
An expression in Qualith is made up of four-line stanzas packed into interlocking blocks, creating complex patterns that are indecipherable by other creatures. Someone that touches a Qualith inscription, however, can receive fragmentary insight into the multilayered thoughts contained within it. A non-illithid that wants to understand a Qualith inscription can make an Intelligence check (DC based on the complexity of the contained thoughts) to try to derive some of the inscription''s meaning. Multiple successful attempts might uncover different aspects about the illithid author, its intended meaning, and its intended audience. A failed attempt results in a crushing headache and, in extreme cases, madness. A {@spell comprehend languages} spell provides understanding of the inscription roughly equivalent to what a mind flayer would get from it.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Quori', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['{@creature inspired|ERLW}', 'kalashtar', '{@filter quori|bestiary|source=ERLW|search=quori}'], (SELECT id FROM language_scripts WHERE name = 'Quori'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Rashemi', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Rashemi ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Riedran', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'standard', ARRAY['people of Sarlona'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Roushoum', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Imaskari ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sahuagin', (SELECT id FROM sources WHERE name = 'MM'), 263, NULL, ARRAY['{@creature sahuagin}', '{@creature Sahuagin Priestess||sahuagin priestesses}', '{@creature Sahuagin Baron||sahuagin barons}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Shaaran', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Shaaran ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Dethek'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Shou', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Shou ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Siren', (SELECT id FROM sources WHERE name = 'PSX'), 17, NULL, ARRAY['{@race Siren|PSX|Sirens}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Slaad', (SELECT id FROM sources WHERE name = 'MM'), 276, NULL, ARRAY['{@creature Slaad Tadpole||slaad tadpoles}', '{@creature Red Slaad||red slaadi}', '{@creature Blue Slaad||blue slaadi}', '{@creature Green Slaad||green slaadi}', '{@creature Gray Slaad||gray slaadi}', '{@creature Death Slaad||death slaadi}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Solamnic', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'standard', ARRAY['Sancrist', 'Solamnia'], (SELECT id FROM language_scripts WHERE name = 'Common'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sphinx', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@creature Sphinx of Judgment|ggr|sphinxes}'], (SELECT id FROM language_scripts WHERE name = 'none'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sphinx', (SELECT id FROM sources WHERE name = 'MM'), 281, NULL, ARRAY['{@creature Gynosphinx||gynosphinxes}', '{@creature Androsphinx||androsphinxes}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sphinx', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Sphinxes'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sylvan', (SELECT id FROM sources WHERE name = 'DSotDQ'), 9, 'rare', ARRAY['Fey creatures'], (SELECT id FROM language_scripts WHERE name = 'Sylvan'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sylvan', (SELECT id FROM sources WHERE name = 'ERLW'), 6, 'exotic', ARRAY['{@filter fey creatures|bestiary|type=fey|source=ERLW}'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sylvan', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@race centaur|ggr|centaurs}', '{@creature Conclave Dryad|ggr|dryads}'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), 'Sylvan is widely spoken in the Selesnya Conclave, for it is rich in vocabulary to describe natural phenomena and spiritual forces.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sylvan', (SELECT id FROM sources WHERE name = 'MOT'), 9, NULL, ARRAY['Centaurs, {@filter satyrs|bestiary|source=MOT|search=satyr}'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Sylvan', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['{@filter fey creatures|bestiary|type=fey}'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Thayan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Mulan ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Thieves'' Cant', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'secret', ARRAY['street gangs', 'Dimir {@class rogue||rogues}', 'Golgari {@class rogue||rogues}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Thieves'' Cant', (SELECT id FROM sources WHERE name = 'PHB'), 94, 'secret', ARRAY['{@creature assassin||assassins}', '{@class rogue||rogues}'], NULL, 'Thieves'' cant is a secret mix of dialect, jargon, and code that allows messages to be hidden in seemingly normal conversation. Only a creature that knows thieves'' cant understands such messages. It takes four times longer to convey such a message than it does to speak the same idea plainly.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Thri-kreen', (SELECT id FROM sources WHERE name = 'MM'), 288, NULL, ARRAY['{@creature thri-kreen}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Tlincalli', (SELECT id FROM sources WHERE name = 'VGM'), 193, NULL, ARRAY['{@creature tlincalli|VGM}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Troglodyte', (SELECT id FROM sources WHERE name = 'MM'), 290, NULL, ARRAY['{@creature Troglodyte||troglodytes}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Tuigan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Tuigan ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Turmic', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Turami ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Uluik', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Ulutiun ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Umber Hulk', (SELECT id FROM sources WHERE name = 'MM'), 292, NULL, ARRAY['{@creature Umber Hulk||umber hulks}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Undercommon', (SELECT id FROM sources WHERE name = 'PHB'), 123, 'exotic', ARRAY['underdark traders'], (SELECT id FROM language_scripts WHERE name = 'Elvish'), '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Untheric', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Mulan ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Vampire', (SELECT id FROM sources WHERE name = 'PSX'), 6, NULL, ARRAY['Legion of Dusk'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Vedalken', (SELECT id FROM sources WHERE name = 'GGR'), 9, 'standard', ARRAY['{@race Vedalken|ggr}'], (SELECT id FROM language_scripts WHERE name = 'Vedalken'), 'The Vedalken language is renowned for its technical treatises and its catalogs of knowledge about the natural world and the aether that pervades it.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Vegepygmy', (SELECT id FROM sources WHERE name = 'VGM'), 196, NULL, ARRAY['{@creature Vegepygmy|VGM|vegepygmies}', '{@creature Vegepygmy Chief|VGM|vegepygmy chiefs}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Waelan', (SELECT id FROM sources WHERE name = 'SCAG'), 112, NULL, ARRAY['Ffolk ethnic group'], (SELECT id FROM language_scripts WHERE name = 'Thorass'), 'Option: Human Languages
Many human ethnicities and nations in Faerûn have their own language, in addition to Common. Most human languages are written in Thorass, the alphabet of Old Common, derived from the Chondathan language that traders used as their common tongue. A few human languages use other alphabets, including Draconic, Dethek, and Espruar.
If your Dungeon Master allows this option, then any human from an ethnic group that has its own language is assumed to know that language as well as Common. This ethnic language is treated as a free additional language for such individuals.');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Winter Wolf', (SELECT id FROM sources WHERE name = 'MM'), 340, NULL, ARRAY['{@creature Winter Wolf||winter wolves}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Worg', (SELECT id FROM sources WHERE name = 'MM'), 341, NULL, ARRAY['{@creature Worg||worgs}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Yeti', (SELECT id FROM sources WHERE name = 'MM'), 305, NULL, ARRAY['{@creature Yeti||yetis}', '{@creature Abominable Yeti||abominable yetis}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Yikaria', (SELECT id FROM sources WHERE name = 'SKT'), 244, NULL, ARRAY['{@creature Yakfolk Priest|SKT|yakfolk priests}', '{@creature Yakfolk Warrior|SKT|yakfolk warriors}'], NULL, '');
INSERT INTO languages (name, source_id, page, type, typical_speakers, script_id, description) VALUES ('Zemnian', (SELECT id FROM sources WHERE name = 'EGW'), 9, NULL, NULL, NULL, 'This ancient language was spoken by the people of Zemniaz in the Age of Arcanum. That ancient culture has long since crumbled, but its language and its people live on in the Dwendalian Empire. Many ancient scrolls were written in Zemnian, but it is a language now largely spoken by farmers, as Common is the default language of the empire.');