-- Source Inserts
INSERT INTO sources (name) VALUES ('ESK');
INSERT INTO sources (name) VALUES ('ScreenDungeonKit');
INSERT INTO sources (name) VALUES ('DMG');
INSERT INTO sources (name) VALUES ('BMT');
INSERT INTO sources (name) VALUES ('DMTCRG');
INSERT INTO sources (name) VALUES ('LLK');
INSERT INTO sources (name) VALUES ('WDMM');
INSERT INTO sources (name) VALUES ('CRCotN');
INSERT INTO sources (name) VALUES ('DIP');
INSERT INTO sources (name) VALUES ('WBtW');
INSERT INTO sources (name) VALUES ('CoS');
INSERT INTO sources (name) VALUES ('TD');
INSERT INTO sources (name) VALUES ('ToA');

-- Decks Inserts
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Combat Step by Step Cards', 1, 3, 1, '${backImageType}', '${backImagePath}', 1640, 2187, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Condition Cards', 1, 3, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Condition Cards', 2, NULL, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Illusions', 3, 161, 0, '${backImageType}', '${backImagePath}', 411, 561, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Many More Things', 4, 51, 1, '${backImageType}', '${backImagePath}', 656, 1123, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Many More Things', 5, 14, 1, '${backImageType}', '${backImagePath}', 656, 1123, '${backImageCredit}');
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Many Things', 4, 12, 1, '${backImageType}', '${backImagePath}', 656, 1123, '${backImageCredit}');
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Many Things', 3, 162, 1, '${backImageType}', '${backImagePath}', 742, 959, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Many Things (13 Cards)', 3, NULL, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Several Things', 6, 53, 0, '${backImageType}', '${backImagePath}', 742, 959, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Deck of Wonder', 4, 55, 1, '${backImageType}', '${backImagePath}', 411, 561, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Elder Runes Deck', 7, 318, 1, '${backImageType}', '${backImagePath}', 411, 561, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Features Deck', 5, 11, 1, '${backImageType}', '${backImagePath}', 656, 1123, '${backImageCredit}');
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Fragments of Suffering', 8, 218, 1, '${backImageType}', '${backImagePath}', 411, 561, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Geomorph Cards', 2, NULL, 1, '${backImageType}', '${backImagePath}', 563, 710, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Hazard Cards', 2, NULL, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Initiative Cards', 1, 3, 1, '${backImageType}', '${backImagePath}', 1567, 2090, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Initiative Cards', 2, NULL, 1, '${backImageType}', '${backImagePath}', 563, 710, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Locations Deck', 5, 11, 1, '${backImageType}', '${backImagePath}', 656, 1123, '${backImageCredit}');
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Magic Charm Cards', 9, 3, 1, '${backImageType}', '${backImagePath}', 1640, 2186, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Magic Item Cards', 9, 3, 1, '${backImageType}', '${backImagePath}', 1647, 2149, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Medals of Merit', 8, 217, 1, '${backImageType}', '${backImagePath}', 411, 561, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Quest Cards', 9, 3, 1, '${backImageType}', '${backImagePath}', 1649, 2199, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Roleplaying Cards', 10, 242, 1, '${backImageType}', '${backImagePath}', 411, 561, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Secrets Deck', 7, 319, 1, '${backImageType}', '${backImagePath}', 411, 561, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Sidekick Cards', 9, 65, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Story Deck', 5, 11, 1, '${backImageType}', '${backImagePath}', 656, 1123, '${backImageCredit}');
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Tarokka Deck', 11, 243, 1, '${backImageType}', '${backImagePath}', 366, 512, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Tarot Deck', 12, 9, 1, '${backImageType}', '${backImagePath}', 720, 1250, NULL);
INSERT INTO decks (name, source_id, page, has_card_art, back_image_type, back_image_path, back_image_width, back_image_height, back_image_credit) VALUES ('Trickster Gods of Omu', 13, 256, 1, '${backImageType}', '${backImagePath}', 411, 561, NULL);

-- Deck cards Inserts
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (1, '${uid}', 0, 3);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (2, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (3, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (4, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (5, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (6, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (7, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (8, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (9, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (10, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (11, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (12, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (13, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (14, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (15, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (16, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (16, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (16, '${uid}', 1, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (17, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (18, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (19, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (20, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, 6);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, 2);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (21, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (22, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (23, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (24, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (25, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (26, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (27, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (28, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (29, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);
INSERT INTO deck_cards (deck_id, uid, replacement, count) VALUES (30, '${uid}', 0, NULL);

-- Deck entries Inserts
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (1, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (1, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (2, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (3, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (4, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (4, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (4, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (4, 3, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (4, 4, 'table', NULL, NULL, NULL, '${tableColLabels}', '${tableColStyles}', '${tableRows}', NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (5, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (5, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (5, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (5, 3, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (5, 4, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (5, 5, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (5, 6, 'table', NULL, NULL, '${tableCaption}', '${tableColLabels}', '${tableColStyles}', '${tableRows}', '${footnotes}', NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (6, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (6, 1, 'list', NULL, '${listItems}', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (6, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (7, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (7, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (7, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (8, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (8, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (8, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (8, 3, 'entries', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '${rawJson}');
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (8, 4, 'table', NULL, NULL, NULL, '${tableColLabels}', '${tableColStyles}', '${tableRows}', '${footnotes}', NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (10, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (10, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (10, 2, 'table', NULL, NULL, NULL, '${tableColLabels}', '${tableColStyles}', '${tableRows}', NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (10, 3, 'inset', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '${rawJson}');
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (11, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (11, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (11, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (11, 3, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (11, 4, 'table', NULL, NULL, '${tableCaption}', '${tableColLabels}', '${tableColStyles}', '${tableRows}', NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (12, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (12, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (12, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (12, 3, 'list', NULL, '${listItems}', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (12, 4, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (12, 5, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (13, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (13, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (14, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (14, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (15, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (16, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (17, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (17, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (18, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (19, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (19, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (20, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (20, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (21, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (21, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (22, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (22, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (23, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (23, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (24, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (24, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (25, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (25, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (25, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (25, 3, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (26, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (26, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (26, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (26, 3, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (26, 4, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (26, 5, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (27, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (27, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (28, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (28, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (28, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (28, 3, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (28, 4, 'section', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '${rawJson}');
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (29, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (29, 1, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (29, 2, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (29, 3, 'entries', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '${rawJson}');
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (29, 4, 'entries', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '${rawJson}');
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (29, 5, 'entries', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '${rawJson}');
INSERT INTO deck_entries (deck_id, entry_order, type, content, list_items, table_caption, table_col_labels, table_col_styles, table_rows, footnotes, raw_json) VALUES (30, 0, 'string', '${content}', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Deck other sources Inserts
INSERT INTO deck_other_sources (deck_id, source_name, page) VALUES (24, 'DoD', 24);

