-- Conditions Inserts
DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Blinded', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 290, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A blinded creature can''t see and automatically fails any ability check that requires sight.","Attack rolls against the creature have advantage, and the creature''s attack rolls have disadvantage."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A blinded creature can''t see and automatically fails any ability check that requires sight.","Attack rolls against the creature have advantage, and the creature''s attack rolls have disadvantage."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Charmed', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 290, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A charmed creature can''t attack the charmer or target the charmer with harmful abilities or magical effects.","The charmer has advantage on any ability check to interact socially with the creature."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A charmed creature can''t attack the charmer or target the charmer with harmful abilities or magical effects.","The charmer has advantage on any ability check to interact socially with the creature."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Deafened', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 290, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A deafened creature can''t hear and automatically fails any ability check that requires hearing."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A deafened creature can''t hear and automatically fails any ability check that requires hearing."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Exhaustion', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 291, true, true, false) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, NULL, NULL, 'Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect''s description.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Some special abilities and environmental hazards, such as starvation and the long-term effects of freezing or scorching temperatures, can lead to a special condition called exhaustion. Exhaustion is measured in six levels. An effect can give a creature one or more levels of exhaustion, as specified in the effect''s description."'::jsonb);
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 1, 'table', NULL, NULL, NULL::jsonb, NULL, '["Level","Effect"]'::jsonb, '[["1","Disadvantage on ability checks"],["2","Speed halved"],["3","Disadvantage on attack rolls and saving throws"],["4","Hit point maximum halved"],["5","Speed reduced to 0"],["6","Death"]]'::jsonb, '{"type":"table","colLabels":["Level","Effect"],"colStyles":["col-1 text-center","col-11"],"rows":[["1","Disadvantage on ability checks"],["2","Speed halved"],["3","Disadvantage on attack rolls and saving throws"],["4","Hit point maximum halved"],["5","Speed reduced to 0"],["6","Death"]]}'::jsonb);
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 2, NULL, NULL, 'If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect''s description.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"If an already exhausted creature suffers another effect that causes exhaustion, its current level of exhaustion increases by the amount specified in the effect''s description."'::jsonb);
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 3, NULL, NULL, 'A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A creature suffers the effect of its current level of exhaustion as well as all lower levels. For example, a creature suffering level 2 exhaustion has its speed halved and has disadvantage on ability checks."'::jsonb);
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 4, NULL, NULL, 'An effect that removes exhaustion reduces its level as specified in the effect''s description, with all exhaustion effects ending if a creature''s exhaustion level is reduced below 1.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"An effect that removes exhaustion reduces its level as specified in the effect''s description, with all exhaustion effects ending if a creature''s exhaustion level is reduced below 1."'::jsonb);
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 5, NULL, NULL, 'Finishing a long rest reduces a creature''s exhaustion level by 1, provided that the creature has also ingested some food and drink. Also, being raised from the dead reduces a creature''s exhaustion level by 1.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Finishing a long rest reduces a creature''s exhaustion level by 1, provided that the creature has also ingested some food and drink. Also, being raised from the dead reduces a creature''s exhaustion level by 1."'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Frightened', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 290, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.","The creature can''t willingly move closer to the source of its fear."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.","The creature can''t willingly move closer to the source of its fear."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Grappled', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 290, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A grappled creature''s speed becomes 0, and it can''t benefit from any bonus to its speed.","The condition ends if the grappler is {@condition incapacitated}.","The condition also ends if an effect removes the grappled creature from the reach of the grappler or grappling effect, such as when a creature is hurled away by the {@spell thunderwave} spell."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A grappled creature''s speed becomes 0, and it can''t benefit from any bonus to its speed.","The condition ends if the grappler is {@condition incapacitated}.","The condition also ends if an effect removes the grappled creature from the reach of the grappler or grappling effect, such as when a creature is hurled away by the {@spell thunderwave} spell."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Incapacitated', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 290, true, true, false) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["An incapacitated creature can''t take actions or reactions."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["An incapacitated creature can''t take actions or reactions."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Invisible', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 291, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["An invisible creature is impossible to see without the aid of magic or a special sense. For the purpose of hiding, the creature is heavily obscured. The creature''s location can be detected by any noise it makes or any tracks it leaves.","Attack rolls against the creature have disadvantage, and the creature''s attack rolls have advantage."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["An invisible creature is impossible to see without the aid of magic or a special sense. For the purpose of hiding, the creature is heavily obscured. The creature''s location can be detected by any noise it makes or any tracks it leaves.","Attack rolls against the creature have disadvantage, and the creature''s attack rolls have advantage."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Paralyzed', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 291, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A paralyzed creature is {@condition incapacitated} and can''t move or speak.","The creature automatically fails Strength and Dexterity saving throws.","Attack rolls against the creature have advantage.","Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A paralyzed creature is {@condition incapacitated} and can''t move or speak.","The creature automatically fails Strength and Dexterity saving throws.","Attack rolls against the creature have advantage.","Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Petrified', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 291, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.","The creature is {@condition incapacitated}, can''t move or speak, and is unaware of its surroundings.","Attack rolls against the creature have advantage.","The creature automatically fails Strength and Dexterity saving throws.","The creature has resistance to all damage.","The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.","The creature is {@condition incapacitated}, can''t move or speak, and is unaware of its surroundings.","Attack rolls against the creature have advantage.","The creature automatically fails Strength and Dexterity saving throws.","The creature has resistance to all damage.","The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Poisoned', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 292, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A poisoned creature has disadvantage on attack rolls and ability checks."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A poisoned creature has disadvantage on attack rolls and ability checks."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Prone', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 292, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A prone creature''s only movement option is to crawl, unless it stands up and thereby ends the condition.","The creature has disadvantage on attack rolls.","An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A prone creature''s only movement option is to crawl, unless it stands up and thereby ends the condition.","The creature has disadvantage on attack rolls.","An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Restrained', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 292, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A restrained creature''s speed becomes 0, and it can''t benefit from any bonus to its speed.","Attack rolls against the creature have advantage, and the creature''s attack rolls have disadvantage.","The creature has disadvantage on Dexterity saving throws."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A restrained creature''s speed becomes 0, and it can''t benefit from any bonus to its speed.","Attack rolls against the creature have advantage, and the creature''s attack rolls have disadvantage.","The creature has disadvantage on Dexterity saving throws."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Stunned', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 292, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["A stunned creature is {@condition incapacitated}, can''t move, and can speak only falteringly.","The creature automatically fails Strength and Dexterity saving throws.","Attack rolls against the creature have advantage."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["A stunned creature is {@condition incapacitated}, can''t move, and can speak only falteringly.","The creature automatically fails Strength and Dexterity saving throws.","Attack rolls against the creature have advantage."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

DO $$
DECLARE
    condition_id_var INTEGER;
BEGIN
    INSERT INTO conditions (name, source_id, page, srd, basic_rules, has_fluff_images) VALUES ('Unconscious', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 292, true, true, true) RETURNING id INTO condition_id_var;
    INSERT INTO condition_entries (condition_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (condition_id_var, 0, 'list', NULL, NULL, '["An unconscious creature is {@condition incapacitated}, can''t move or speak, and is unaware of its surroundings.","The creature drops whatever it''s holding and falls {@condition prone}.","The creature automatically fails Strength and Dexterity saving throws.","Attack rolls against the creature have advantage.","Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature."]'::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"list","items":["An unconscious creature is {@condition incapacitated}, can''t move or speak, and is unaware of its surroundings.","The creature drops whatever it''s holding and falls {@condition prone}.","The creature automatically fails Strength and Dexterity saving throws.","Attack rolls against the creature have advantage.","Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature."]}'::jsonb);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'RMR', 62);
    INSERT INTO condition_other_sources (condition_id, source_name, page) VALUES (condition_id_var, 'HftT', 48);
END $$;

-- Diseases Inserts
DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Arcane Blight', (SELECT id FROM sources WHERE name ILIKE 'IDRotF' LIMIT 1), 233) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Any humanoid that spends 12 hours in the necropolis must succeed on a {@dc 15} Constitution saving throw or contract an arcane blight. This magical disease transforms the humanoid into a {@creature nothic}, but only after the victim experiences hallucinations and feelings of isolation and paranoia. Other symptoms include clammy skin, hair loss, and myopia (nearsightedness).', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Any humanoid that spends 12 hours in the necropolis must succeed on a {@dc 15} Constitution saving throw or contract an arcane blight. This magical disease transforms the humanoid into a {@creature nothic}, but only after the victim experiences hallucinations and feelings of isolation and paranoia. Other symptoms include clammy skin, hair loss, and myopia (nearsightedness)."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'A player character infected with the arcane blight gains the following flaw: "I don''t trust anyone." This flaw, which supersedes any conflicting flaw, is fed by delusions that are difficult for the character to distinguish from reality. Common delusions include the belief that that allies are conspiring to steal the victim''s riches or otherwise turn against the victim.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A player character infected with the arcane blight gains the following flaw: \"I don''t trust anyone.\" This flaw, which supersedes any conflicting flaw, is fed by delusions that are difficult for the character to distinguish from reality. Common delusions include the belief that that allies are conspiring to steal the victim''s riches or otherwise turn against the victim."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'Whenever it finishes a long rest, an infected humanoid must repeat the saving throw. On a successful save, the DC for future saves against the arcane blight drops by {@dice 1d6}. If the saving throw DC drops to 0, the creature overcomes the arcane blight and becomes immune to the effect of further exposure. A creature that fails three of these saving throws transforms into a {@creature nothic} under the DM''s control. Only a {@spell wish} spell or divine intervention can undo this transformation.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Whenever it finishes a long rest, an infected humanoid must repeat the saving throw. On a successful save, the DC for future saves against the arcane blight drops by {@dice 1d6}. If the saving throw DC drops to 0, the creature overcomes the arcane blight and becomes immune to the effect of further exposure. A creature that fails three of these saving throws transforms into a {@creature nothic} under the DM''s control. Only a {@spell wish} spell or divine intervention can undo this transformation."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 3, NULL, NULL, 'A {@spell greater restoration} spell or similar magic ends the infection on the target, removing the flaw and all other symptoms, but this magic doesn''t protect the target against further exposure.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A {@spell greater restoration} spell or similar magic ends the infection on the target, removing the flaw and all other symptoms, but this magic doesn''t protect the target against further exposure."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Blinding Sickness', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 227) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Pain grips the creature''s mind, and its eyes turn milky white. The creature has disadvantage on Wisdom checks and Wisdom saving throws and is {@condition blinded}.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Pain grips the creature''s mind, and its eyes turn milky white. The creature has disadvantage on Wisdom checks and Wisdom saving throws and is {@condition blinded}."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, '{@note This disease can be inflicted with the {@spell contagion} spell.}', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"{@note This disease can be inflicted with the {@spell contagion} spell.}"'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Blue Mist Fever', (SELECT id FROM sources WHERE name ILIKE 'ToA' LIMIT 1), 40) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'A magical mist creeps through the jungles of Chult. Contact with this thin, blue, odorless mist can infect giants and humanoids with blue mist fever. A {@spell dispel magic} spell destroys the mist in a 20-foot square starting at a point chosen by the caster within the spell''s range. An encounter with this mist typically covers {@dice 1d6} such areas (400-2,400 square feet).', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A magical mist creeps through the jungles of Chult. Contact with this thin, blue, odorless mist can infect giants and humanoids with blue mist fever. A {@spell dispel magic} spell destroys the mist in a 20-foot square starting at a point chosen by the caster within the spell''s range. An encounter with this mist typically covers {@dice 1d6} such areas (400-2,400 square feet)."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'A giant or humanoid that comes into contact with the mist must succeed on a {@dc 13} Constitution saving throw or become infected with blue mist fever. An infected creature begins seeing vivid hallucinations of blue monkeys {@dice 1d6} hours after failing the save, and the hallucinations last until the disease ends on the creature. A creature can repeat the saving throw every 24 hours, ending the effect on itself on a success.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A giant or humanoid that comes into contact with the mist must succeed on a {@dc 13} Constitution saving throw or become infected with blue mist fever. An infected creature begins seeing vivid hallucinations of blue monkeys {@dice 1d6} hours after failing the save, and the hallucinations last until the disease ends on the creature. A creature can repeat the saving throw every 24 hours, ending the effect on itself on a success."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Bluerot', (SELECT id FROM sources WHERE name ILIKE 'GoS' LIMIT 1), 234) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'This disease targets humanoids. While afflicted with bluerot, a victim grows grotesque blue boils on their face and back. This disease is carried by undead (including the drowned ones in Tammeraut''s Fate), and victims most often acquire it through wounds caused by infected creatures. The disease''s boils manifest in {@dice 1d4} hours, causing the victim''s Constitution and Charisma scores to decrease by {@dice 1d4} each, to a minimum of 3. This is quickly followed by a fever and tingling in the extremities. An infected creature is vulnerable to radiant damage and gains the ability to breathe underwater.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"This disease targets humanoids. While afflicted with bluerot, a victim grows grotesque blue boils on their face and back. This disease is carried by undead (including the drowned ones in Tammeraut''s Fate), and victims most often acquire it through wounds caused by infected creatures. The disease''s boils manifest in {@dice 1d4} hours, causing the victim''s Constitution and Charisma scores to decrease by {@dice 1d4} each, to a minimum of 3. This is quickly followed by a fever and tingling in the extremities. An infected creature is vulnerable to radiant damage and gains the ability to breathe underwater."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'At the end of each long rest, an infected creature makes a {@dc 12} Constitution saving throw. On a success, the victim regains 1 point of Constitution and 1 point of Charisma lost to the disease. If the infected creature regains all the points lost to the disease, it is cured. Other effects that raise the victim''s ability scores do not cure the disease. On a failed saving throw, the victim takes 18 ({@damage 4d8}) necrotic damage as the boils burst and spread. A creature reduced to 0 hit points by this damage cannot regain hit points until the disease is cured, though it can be stabilized as normal.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"At the end of each long rest, an infected creature makes a {@dc 12} Constitution saving throw. On a success, the victim regains 1 point of Constitution and 1 point of Charisma lost to the disease. If the infected creature regains all the points lost to the disease, it is cured. Other effects that raise the victim''s ability scores do not cure the disease. On a failed saving throw, the victim takes 18 ({@damage 4d8}) necrotic damage as the boils burst and spread. A creature reduced to 0 hit points by this damage cannot regain hit points until the disease is cured, though it can be stabilized as normal."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Cackle Fever', (SELECT id FROM sources WHERE name ILIKE 'DMG' LIMIT 1), 257) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'This disease targets humanoids, although gnomes are strangely immune. While in the grips of this disease, victims frequently succumb to fits of mad laughter, giving the disease its common name and its morbid nickname: "the shrieks."', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"This disease targets humanoids, although gnomes are strangely immune. While in the grips of this disease, victims frequently succumb to fits of mad laughter, giving the disease its common name and its morbid nickname: \"the shrieks.\""'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'Symptoms manifest {@dice 1d4} hours after infection and include fever and disorientation. The infected creature gains one level of {@condition exhaustion} that can''t be removed until the disease is cured.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Symptoms manifest {@dice 1d4} hours after infection and include fever and disorientation. The infected creature gains one level of {@condition exhaustion} that can''t be removed until the disease is cured."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'Any event that causes the infected creature great stress—including entering combat, taking damage, experiencing fear, or having a nightmare—forces the creature to make a {@dc 13} Constitution saving throw.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Any event that causes the infected creature great stress—including entering combat, taking damage, experiencing fear, or having a nightmare—forces the creature to make a {@dc 13} Constitution saving throw."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 3, NULL, NULL, 'On a failed save, the creature takes 5 ({@dice 1d10}) psychic damage and becomes {@condition incapacitated} with mad laughter for 1 minute. The creature can repeat the saving throw at the end of each of its turns, ending the mad laughter and the {@condition incapacitated} condition on a success. Any humanoid creature that starts its turn within 10 feet of an infected creature in the throes of mad laughter must succeed on a {@dc 10} Constitution saving throw or also become infected with the disease. Once a creature succeeds on this save, it is immune to the mad laughter of that particular infected creature for 24 hours.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"On a failed save, the creature takes 5 ({@dice 1d10}) psychic damage and becomes {@condition incapacitated} with mad laughter for 1 minute. The creature can repeat the saving throw at the end of each of its turns, ending the mad laughter and the {@condition incapacitated} condition on a success. Any humanoid creature that starts its turn within 10 feet of an infected creature in the throes of mad laughter must succeed on a {@dc 10} Constitution saving throw or also become infected with the disease. Once a creature succeeds on this save, it is immune to the mad laughter of that particular infected creature for 24 hours."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 4, NULL, NULL, 'At the end of each long rest, an infected creature can make a {@dc 13} Constitution saving throw. On a successful save, the DC for this save and for the save to avoid an attack of mad laughter drops by {@dice 1d6}. When the saving throw DC drops to 0, the creature recovers from the disease. A creature that fails three of these saving throws gains a randomly determined form of {@variantrule Madness|DMG|indefinite madness}.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"At the end of each long rest, an infected creature can make a {@dc 13} Constitution saving throw. On a successful save, the DC for this save and for the save to avoid an attack of mad laughter drops by {@dice 1d6}. When the saving throw DC drops to 0, the creature recovers from the disease. A creature that fails three of these saving throws gains a randomly determined form of {@variantrule Madness|DMG|indefinite madness}."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Filth Fever', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 227) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'A raging fever sweeps through the creature''s body. The creature has disadvantage on Strength checks, Strength saving throws, and attack rolls that use Strength.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A raging fever sweeps through the creature''s body. The creature has disadvantage on Strength checks, Strength saving throws, and attack rolls that use Strength."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, '{@note This disease can be inflicted with the {@spell contagion} spell.}', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"{@note This disease can be inflicted with the {@spell contagion} spell.}"'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Flesh Rot', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 227) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'The creature''s flesh decays. The creature has disadvantage on Charisma checks and vulnerability to all damage.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The creature''s flesh decays. The creature has disadvantage on Charisma checks and vulnerability to all damage."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, '{@note This disease can be inflicted with the {@spell contagion} spell.}', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"{@note This disease can be inflicted with the {@spell contagion} spell.}"'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Frigid Woe', (SELECT id FROM sources WHERE name ILIKE 'EGW' LIMIT 1), 125) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Frigid woe is a special disease developed by Aeor''s mages that cannot be cured by conventional treatment or magic. The only way a creature infected with the disease can be cured is by finding and drinking the manufactured antidote, a milky liquid stored in gold vials found in Eiselcross''s ruins. This disease was created to slow down the forces of the gods and get around the healing power of their clerics and angels.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Frigid woe is a special disease developed by Aeor''s mages that cannot be cured by conventional treatment or magic. The only way a creature infected with the disease can be cured is by finding and drinking the manufactured antidote, a milky liquid stored in gold vials found in Eiselcross''s ruins. This disease was created to slow down the forces of the gods and get around the healing power of their clerics and angels."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'The disease is transmitted by breathing in blue spores that Aeor''s mages created long ago. When a creature comes into contact with these spores, it must succeed on a {@dc 11} Constitution saving throw or become infected with frigid woe. It takes {@dice 1d4} days for the symptoms to manifest in an infected creature. These symptoms include fatigue, chills, and visible blue veins that appear on the creature''s body. The infected creature''s speed is reduced by 5 feet as long as it remains infected. Every 10 days after symptoms appear, an infected creature must succeed on a {@dc 11} Constitution saving throw, or its speed is reduced by another 5 feet. If a creature''s speed is reduced to 0 as a result of this disease, the creature dies and its body turns into a statue made of ice.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The disease is transmitted by breathing in blue spores that Aeor''s mages created long ago. When a creature comes into contact with these spores, it must succeed on a {@dc 11} Constitution saving throw or become infected with frigid woe. It takes {@dice 1d4} days for the symptoms to manifest in an infected creature. These symptoms include fatigue, chills, and visible blue veins that appear on the creature''s body. The infected creature''s speed is reduced by 5 feet as long as it remains infected. Every 10 days after symptoms appear, an infected creature must succeed on a {@dc 11} Constitution saving throw, or its speed is reduced by another 5 feet. If a creature''s speed is reduced to 0 as a result of this disease, the creature dies and its body turns into a statue made of ice."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'A creature can drink the antidote as an action, ending all symptoms and effects of the disease instantly.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A creature can drink the antidote as an action, ending all symptoms and effects of the disease instantly."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Ghoul Gut', (SELECT id FROM sources WHERE name ILIKE 'OoW' LIMIT 1), 111) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Water polluted with ghoul parts carries ghoul gut. A creature drinking this tainted water must succeed on a {@dc 12} Constitution saving throw or contract the disease. Symptoms strike when a victim starts a long rest or next becomes excited, as during combat. A victim suffers severe cramps, and their bowels make sounds like two ghouls fighting. When the symptoms first strike, the victim takes 5 ({@damage 2d4}) necrotic damage. In addition, a diseased victim regains no hit points or Hit Dice from nonmagical sources, including resting or spending Hit Dice. A victim who finishes a long rest can attempt a {@dc 12} Constitution saving throw. On a successful save, the victim shakes off the disease. Failure deals the character another 5 ({@damage 2d4}) necrotic damage.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Water polluted with ghoul parts carries ghoul gut. A creature drinking this tainted water must succeed on a {@dc 12} Constitution saving throw or contract the disease. Symptoms strike when a victim starts a long rest or next becomes excited, as during combat. A victim suffers severe cramps, and their bowels make sounds like two ghouls fighting. When the symptoms first strike, the victim takes 5 ({@damage 2d4}) necrotic damage. In addition, a diseased victim regains no hit points or Hit Dice from nonmagical sources, including resting or spending Hit Dice. A victim who finishes a long rest can attempt a {@dc 12} Constitution saving throw. On a successful save, the victim shakes off the disease. Failure deals the character another 5 ({@damage 2d4}) necrotic damage."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'A character who succeeds on a {@dc 15} Wisdom ({@skill Medicine}) check can also remove the disease from another creature. Doing so requires the character making the check to care for the sick individual during a long rest. The caregiver gains no benefit from that rest.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A character who succeeds on a {@dc 15} Wisdom ({@skill Medicine}) check can also remove the disease from another creature. Doing so requires the character making the check to care for the sick individual during a long rest. The caregiver gains no benefit from that rest."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Grackle-Lung', (SELECT id FROM sources WHERE name ILIKE 'OotA' LIMIT 1), 54) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'The constant smog in Gracklstugh causes grackle-lung in living, breathing creatures, resulting in persistent, wracking coughs and the spewing of thick, black phlegm. Whenever a living, breathing creature finishes a long rest in Gracklstugh, it must make a {@dc 11} Constitution saving throw. On each failed save, the creature gains one level of {@condition exhaustion} as its airways become increasingly clogged. A creature that reaches level 6 {@condition exhaustion} dies, as normal.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The constant smog in Gracklstugh causes grackle-lung in living, breathing creatures, resulting in persistent, wracking coughs and the spewing of thick, black phlegm. Whenever a living, breathing creature finishes a long rest in Gracklstugh, it must make a {@dc 11} Constitution saving throw. On each failed save, the creature gains one level of {@condition exhaustion} as its airways become increasingly clogged. A creature that reaches level 6 {@condition exhaustion} dies, as normal."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'A creature with one or more levels of {@condition exhaustion} brought on by grackle-lung must succeed on a Constitution check to take the {@action Dash} action. If the check fails, the action cannot be attempted. If the creature attempts to cast a spell with a verbal component, it must succeed on a Constitution check or be unable to complete the spell, causing the spell to fail with no effect. The DC for each check is 10 + the creature''s current {@condition exhaustion} level.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A creature with one or more levels of {@condition exhaustion} brought on by grackle-lung must succeed on a Constitution check to take the {@action Dash} action. If the check fails, the action cannot be attempted. If the creature attempts to cast a spell with a verbal component, it must succeed on a Constitution check or be unable to complete the spell, causing the spell to fail with no effect. The DC for each check is 10 + the creature''s current {@condition exhaustion} level."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'If a creature''s {@condition exhaustion} level drops below 1, it no longer suffers the effects of grackle-lung and becomes immune to it for the next week. Duergar and derro are inured to grackle-lung, making Constitution checks against it with advantage. Any spell or effect that cures disease also cures grackle-lung, effectively removing all levels of {@condition exhaustion} brought on by the affliction.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"If a creature''s {@condition exhaustion} level drops below 1, it no longer suffers the effects of grackle-lung and becomes immune to it for the next week. Duergar and derro are inured to grackle-lung, making Constitution checks against it with advantage. Any spell or effect that cures disease also cures grackle-lung, effectively removing all levels of {@condition exhaustion} brought on by the affliction."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Mindfire', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 227) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'The creature''s mind becomes feverish. The creature has disadvantage on Intelligence checks and Intelligence saving throws, and the creature behaves as if under the effects of the {@spell confusion} spell during combat.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The creature''s mind becomes feverish. The creature has disadvantage on Intelligence checks and Intelligence saving throws, and the creature behaves as if under the effects of the {@spell confusion} spell during combat."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, '{@note This disease can be inflicted with the {@spell contagion} spell.}', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"{@note This disease can be inflicted with the {@spell contagion} spell.}"'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Redface', (SELECT id FROM sources WHERE name ILIKE 'GoS' LIMIT 1), 168) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'The effects of redface are identical to those of {@disease sight rot} (see "{@book Diseases|DMG|8|Diseases}" in chapter 8 of the {@book Dungeon Master''s Guide|DMG}), but it''s caused by pollutants in the air rather than contaminated drinking water, making it difficult to avoid.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The effects of redface are identical to those of {@disease sight rot} (see \"{@book Diseases|DMG|8|Diseases}\" in chapter 8 of the {@book Dungeon Master''s Guide|DMG}), but it''s caused by pollutants in the air rather than contaminated drinking water, making it difficult to avoid."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Saprophytic Plague', (SELECT id FROM sources WHERE name ILIKE 'CM' LIMIT 1), 253) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Xanthoria''s research into lichdom and her creation of a living phylactery led to the emergence of the plague spreading across the Sword Coast. Any beast or humanoid that comes within 10 feet of a creature infected by the saprophytic plague must succeed on a {@dc 20} Constitution saving throw or become infected as well. On a successful save, a creature is immune to the plague for 24 hours, and any creature that is immune to disease succeeds on the save automatically.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Xanthoria''s research into lichdom and her creation of a living phylactery led to the emergence of the plague spreading across the Sword Coast. Any beast or humanoid that comes within 10 feet of a creature infected by the saprophytic plague must succeed on a {@dc 20} Constitution saving throw or become infected as well. On a successful save, a creature is immune to the plague for 24 hours, and any creature that is immune to disease succeeds on the save automatically."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'After a failed save, a creature experiences the first symptoms—body aches, nausea, slurred speech, and uncontrollable drooling—{@dice 1d4} hours later and gains 1 level of {@condition exhaustion}. Every 24 hours thereafter, the creature automatically gains another level of {@condition exhaustion}. Any creature killed by the saprophytic plague transforms into a lifeless magenta ooze.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"After a failed save, a creature experiences the first symptoms—body aches, nausea, slurred speech, and uncontrollable drooling—{@dice 1d4} hours later and gains 1 level of {@condition exhaustion}. Every 24 hours thereafter, the creature automatically gains another level of {@condition exhaustion}. Any creature killed by the saprophytic plague transforms into a lifeless magenta ooze."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'A creature infected by the saprophytic plague for at least 24 hours behaves like a zombie and seems barely aware of its surroundings, as fungal growths sprout from its head, body, and limbs. It feels an overriding urge to be around groups of uninfected creatures so that it can spread the contagion. This is the time when infected humanoids begin speaking the word "Xanthoria" over and over, with no understanding of what the word means. This behavior is the result of a mycelial network of spores that forms a tenuous connection between Xanthoria and humanoids that become infected by the plague.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A creature infected by the saprophytic plague for at least 24 hours behaves like a zombie and seems barely aware of its surroundings, as fungal growths sprout from its head, body, and limbs. It feels an overriding urge to be around groups of uninfected creatures so that it can spread the contagion. This is the time when infected humanoids begin speaking the word \"Xanthoria\" over and over, with no understanding of what the word means. This behavior is the result of a mycelial network of spores that forms a tenuous connection between Xanthoria and humanoids that become infected by the plague."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 3, NULL, NULL, 'Foodstuffs that are exposed to the plague''s spores decay or go sour within {@dice 2d12} hours, leaving behind a lurid magenta mass of oozing fungi. Eating infected food requires a saving throw as above.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Foodstuffs that are exposed to the plague''s spores decay or go sour within {@dice 2d12} hours, leaving behind a lurid magenta mass of oozing fungi. Eating infected food requires a saving throw as above."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 4, NULL, NULL, 'Any magic that cures a disease can rid a creature of the saprophytic plague. Casting {@spell purify food and drink} destroys the infection in foodstuffs.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Any magic that cures a disease can rid a creature of the saprophytic plague. Casting {@spell purify food and drink} destroys the infection in foodstuffs."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Seizure', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 227) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'The creature is overcome with shaking. The creature has disadvantage on Dexterity checks, Dexterity saving throws, and attack rolls that use Dexterity.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The creature is overcome with shaking. The creature has disadvantage on Dexterity checks, Dexterity saving throws, and attack rolls that use Dexterity."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, '{@note This disease can be inflicted with the {@spell contagion} spell.}', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"{@note This disease can be inflicted with the {@spell contagion} spell.}"'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Sewer Plague', (SELECT id FROM sources WHERE name ILIKE 'DMG' LIMIT 1), 257) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Sewer plague is a generic term for a broad category of illnesses that incubate in sewers, refuse heaps, and stagnant swamps, and which are sometimes transmitted by creatures that dwell in those areas, such as rats and otyughs.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Sewer plague is a generic term for a broad category of illnesses that incubate in sewers, refuse heaps, and stagnant swamps, and which are sometimes transmitted by creatures that dwell in those areas, such as rats and otyughs."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'When a humanoid creature is bitten by a creature that carries the disease, or when it comes into contact with filth or offal contaminated by the disease, the creature must succeed on a {@dc 11} Constitution saving throw or become infected.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"When a humanoid creature is bitten by a creature that carries the disease, or when it comes into contact with filth or offal contaminated by the disease, the creature must succeed on a {@dc 11} Constitution saving throw or become infected."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'It takes {@dice 1d4} days for sewer plague''s symptoms to manifest in an infected creature. Symptoms include fatigue and cramps. The infected creature suffers one level of {@condition exhaustion}, and it regains only half the normal number of hit points from spending Hit Dice and no hit points from finishing a long rest.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"It takes {@dice 1d4} days for sewer plague''s symptoms to manifest in an infected creature. Symptoms include fatigue and cramps. The infected creature suffers one level of {@condition exhaustion}, and it regains only half the normal number of hit points from spending Hit Dice and no hit points from finishing a long rest."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 3, NULL, NULL, 'At the end of each long rest, an infected creature must make a {@dc 11} Constitution saving throw. On a failed save, the character gains one level of {@condition exhaustion}.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"At the end of each long rest, an infected creature must make a {@dc 11} Constitution saving throw. On a failed save, the character gains one level of {@condition exhaustion}."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 4, NULL, NULL, 'On a successful save, the character''s {@condition exhaustion} level decreases by one level. If a successful saving throw reduces the infected creature''s level of {@condition exhaustion} below 1, the creature recovers from the disease.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"On a successful save, the character''s {@condition exhaustion} level decreases by one level. If a successful saving throw reduces the infected creature''s level of {@condition exhaustion} below 1, the creature recovers from the disease."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Shivering Sickness', (SELECT id FROM sources WHERE name ILIKE 'ToA' LIMIT 1), 40) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Insects native to the jungles and marshes of Chult carry this disease, shivering sickness. The easiest protection against it is a coating of insect-repelling salve on all exposed skin (for the cost of insect repellent, see {@adventure "Buying a Special Item"|ToA|1|Buying a Special Item}.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Insects native to the jungles and marshes of Chult carry this disease, shivering sickness. The easiest protection against it is a coating of insect-repelling salve on all exposed skin (for the cost of insect repellent, see {@adventure \"Buying a Special Item\"|ToA|1|Buying a Special Item}."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'A giant or humanoid that takes damage from {@creature Swarm of Insects||insect swarms} or from {@creature giant centipede||giant centipedes}, {@creature giant scorpion||giant scorpions}, or {@creature giant wasp||giant wasps} is exposed to the disease at the end of the encounter. Those who haven''t applied insect repellent since their previous long rest are exposed to the disease when they finish a long rest.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A giant or humanoid that takes damage from {@creature Swarm of Insects||insect swarms} or from {@creature giant centipede||giant centipedes}, {@creature giant scorpion||giant scorpions}, or {@creature giant wasp||giant wasps} is exposed to the disease at the end of the encounter. Those who haven''t applied insect repellent since their previous long rest are exposed to the disease when they finish a long rest."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'A giant or humanoid exposed to the disease must succeed on a {@dc 11} Constitution saving throw or become infected. A creature with natural armor has advantage on the saving throw. It takes {@dice 2d6} hours for symptoms to manifest in an infected creature. Symptoms include blurred vision, disorientation, and a sudden drop in body temperature that causes uncontrollable shivering and chattering of the teeth.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A giant or humanoid exposed to the disease must succeed on a {@dc 11} Constitution saving throw or become infected. A creature with natural armor has advantage on the saving throw. It takes {@dice 2d6} hours for symptoms to manifest in an infected creature. Symptoms include blurred vision, disorientation, and a sudden drop in body temperature that causes uncontrollable shivering and chattering of the teeth."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 3, NULL, NULL, 'Once symptoms begin, the infected creature regains only half the normal number of hit points from spending Hit Dice and no hit points from a long rest. The infected creature also has disadvantage on ability checks and attack rolls. At the end of a long rest, an infected creature repeats the saving throw, shaking off the disease on a successful save.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Once symptoms begin, the infected creature regains only half the normal number of hit points from spending Hit Dice and no hit points from a long rest. The infected creature also has disadvantage on ability checks and attack rolls. At the end of a long rest, an infected creature repeats the saving throw, shaking off the disease on a successful save."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Sight Rot', (SELECT id FROM sources WHERE name ILIKE 'DMG' LIMIT 1), 257) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'This painful infection causes bleeding from the eyes and eventually blinds the victim.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"This painful infection causes bleeding from the eyes and eventually blinds the victim."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'A beast or humanoid that drinks water tainted by sight rot must succeed on a {@dc 15} Constitution saving throw or become infected. One day after infection, the creature''s vision starts to become blurry. The creature takes a -1 penalty to attack rolls and ability checks that rely on sight. At the end of each long rest after the symptoms appear, the penalty worsens by 1. When it reaches -5, the victim is {@condition blinded} until its sight is restored by magic such as {@spell lesser restoration} or {@spell heal}.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A beast or humanoid that drinks water tainted by sight rot must succeed on a {@dc 15} Constitution saving throw or become infected. One day after infection, the creature''s vision starts to become blurry. The creature takes a -1 penalty to attack rolls and ability checks that rely on sight. At the end of each long rest after the symptoms appear, the penalty worsens by 1. When it reaches -5, the victim is {@condition blinded} until its sight is restored by magic such as {@spell lesser restoration} or {@spell heal}."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, NULL, NULL, 'Sight rot can be cured using a rare flower called Eyebright, which grows in some swamps. Given an hour, a character who has proficiency with an {@item herbalism kit|phb} can turn the flower into one dose of ointment. Applied to the eyes before a long rest, one dose of it prevents the disease from worsening after that rest. After three doses, the ointment cures the disease entirely.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Sight rot can be cured using a rare flower called Eyebright, which grows in some swamps. Given an hour, a character who has proficiency with an {@item herbalism kit|phb} can turn the flower into one dose of ointment. Applied to the eyes before a long rest, one dose of it prevents the disease from worsening after that rest. After three doses, the ointment cures the disease entirely."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Slimy Doom', (SELECT id FROM sources WHERE name ILIKE 'PHB' LIMIT 1), 227) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'The creature begins to bleed uncontrollably. The creature has disadvantage on Constitution checks and Constitution saving throws. In addition, whenever the creature takes damage, it is {@condition stunned} until the end of its next turn.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The creature begins to bleed uncontrollably. The creature has disadvantage on Constitution checks and Constitution saving throws. In addition, whenever the creature takes damage, it is {@condition stunned} until the end of its next turn."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, '{@note This disease can be inflicted with the {@spell contagion} spell.}', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"{@note This disease can be inflicted with the {@spell contagion} spell.}"'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Spider Eggs', (SELECT id FROM sources WHERE name ILIKE 'WDMM' LIMIT 1), 47) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'If the party is defeated, stabilized characters awaken after {@dice 1d4} hours to find themselves cocooned in sticky webs and suspended 10 feet off the floor, with spider eggs implanted in their bodies. A cocooned character is {@condition restrained} and can use its action to try to escape by making a successful {@dc 15} Strength check.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"If the party is defeated, stabilized characters awaken after {@dice 1d4} hours to find themselves cocooned in sticky webs and suspended 10 feet off the floor, with spider eggs implanted in their bodies. A cocooned character is {@condition restrained} and can use its action to try to escape by making a successful {@dc 15} Strength check."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'Spider eggs implanted in a host hatch in {@dice 2d12} hours, killing the host as the baby spiders chew their way out. This infestation functions like a disease. A {@spell lesser restoration} spell or similar magic cast upon the host kills the spider eggs, ending the threat.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Spider eggs implanted in a host hatch in {@dice 2d12} hours, killing the host as the baby spiders chew their way out. This infestation functions like a disease. A {@spell lesser restoration} spell or similar magic cast upon the host kills the spider eggs, ending the threat."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Super-Tetanus', (SELECT id FROM sources WHERE name ILIKE 'TftYP' LIMIT 1), 104) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'A creature that contracts the disease of super-tetanus is wracked with pain as its heart races and its muscles spasm hard enough to break its bones. The creature takes 11 ({@damage 2d10}) damage at the start of each of its turns. If a victim is not cured by other means, it can repeat the saving throw at the end of every minute after becoming exposed, ending the effect on itself with a successful save.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"A creature that contracts the disease of super-tetanus is wracked with pain as its heart races and its muscles spasm hard enough to break its bones. The creature takes 11 ({@damage 2d10}) damage at the start of each of its turns. If a victim is not cured by other means, it can repeat the saving throw at the end of every minute after becoming exposed, ending the effect on itself with a successful save."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('The Gnawing Plague', (SELECT id FROM sources WHERE name ILIKE 'VRGR' LIMIT 1), 153) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'The Gnawing Plague, also known as "the Gnaws," is known in every corner of Richemulot.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"The Gnawing Plague, also known as \"the Gnaws,\" is known in every corner of Richemulot."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, 'entries', 'Transmission', 'The Gnaws is spread when a creature is bitten by a {@creature rat}, {@creature giant rat}, {@creature swarm of rats}, or {@creature wererat} that carries the disease, or by coming into physical contact with an infected creature.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"entries","name":"Transmission","page":153,"entries":["The Gnaws is spread when a creature is bitten by a {@creature rat}, {@creature giant rat}, {@creature swarm of rats}, or {@creature wererat} that carries the disease, or by coming into physical contact with an infected creature."]}'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 2, 'entries', 'Infection', 'Creatures exposed to the disease must succeed on a {@dc 10} Constitution saving throw or become infected. The DC of this saving throw can increase depending on the severity of the plague''s spread (see "{@book Cycle of the Plague|VRGR|3|Cycle of the Plague}" below).', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"entries","name":"Infection","page":153,"entries":["Creatures exposed to the disease must succeed on a {@dc 10} Constitution saving throw or become infected. The DC of this saving throw can increase depending on the severity of the plague''s spread (see \"{@book Cycle of the Plague|VRGR|3|Cycle of the Plague}\" below)."]}'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 3, 'entries', 'Symptoms', 'It takes {@dice 1d2} days for the Gnawing Plague''s symptoms to manifest in an infected creature. The infected creature then gains 1 level of {@condition exhaustion}, regains only half the normal number of hit points from spending Hit Dice, and regains no hit points from finishing a long rest.
The plague''s symptoms include buboes, fatigue, splotchy rashes, sweats, and shaking, particularly facial tremors. Locals liken these twitches to the sniffing of rats. Sufferers often have scraps of leather placed in their mouths to prevent their teeth from clattering, though they inevitably gnaw through these scraps.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"entries","name":"Symptoms","page":153,"entries":["It takes {@dice 1d2} days for the Gnawing Plague''s symptoms to manifest in an infected creature. The infected creature then gains 1 level of {@condition exhaustion}, regains only half the normal number of hit points from spending Hit Dice, and regains no hit points from finishing a long rest.","The plague''s symptoms include buboes, fatigue, splotchy rashes, sweats, and shaking, particularly facial tremors. Locals liken these twitches to the sniffing of rats. Sufferers often have scraps of leather placed in their mouths to prevent their teeth from clattering, though they inevitably gnaw through these scraps."]}'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 4, 'entries', 'Recovery', 'At the end of each long rest, an infected creature must make a {@dc 10} Constitution saving throw. On a failed save, the creature gains 1 level of {@condition exhaustion}. On a successful save, the creature''s {@condition exhaustion} level decreases by 1. If a successful saving throw reduces the infected creature''s level of {@condition exhaustion} below 1, the creature recovers from the disease.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"entries","name":"Recovery","page":154,"entries":["At the end of each long rest, an infected creature must make a {@dc 10} Constitution saving throw. On a failed save, the creature gains 1 level of {@condition exhaustion}. On a successful save, the creature''s {@condition exhaustion} level decreases by 1. If a successful saving throw reduces the infected creature''s level of {@condition exhaustion} below 1, the creature recovers from the disease."]}'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 5, 'entries', 'Immunity', 'All forms of rats and wererats are immune to the Gnawing Plague.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '{"type":"entries","name":"Immunity","page":154,"entries":["All forms of rats and wererats are immune to the Gnawing Plague."]}'::jsonb);
END $DISEASE_INSERT_BLOCK$;

DO $DISEASE_INSERT_BLOCK$
DECLARE
    disease_id_var INTEGER;
BEGIN
    INSERT INTO diseases (name, source_id, page) VALUES ('Throat Leeches', (SELECT id FROM sources WHERE name ILIKE 'ToA' LIMIT 1), 40) RETURNING id INTO disease_id_var;
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 0, NULL, NULL, 'Minuscule parasites known as throat leeches infect the water in Chult''s forests, swamps, and rivers. Any giant or humanoid that swallows tainted water must succeed on a {@dc 12} Constitution saving throw or be infested with throat leeches. Immediate symptoms include throat inflammation and shortness of breath. After {@dice 1d6} hours, the infected character gains 1 level of {@condition exhaustion} that can''t be removed (except as described below) until the disease is cured. At the end of each long rest, the infected creature must repeat the saving throw. On a failed save, the creature''s {@condition exhaustion} increases by 1 level; on a successful save, the creature''s {@condition exhaustion} decreases by 1 level. If a successful saving throw reduces the infected creature''s level of {@condition exhaustion} below 1, the creature recovers from the disease.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Minuscule parasites known as throat leeches infect the water in Chult''s forests, swamps, and rivers. Any giant or humanoid that swallows tainted water must succeed on a {@dc 12} Constitution saving throw or be infested with throat leeches. Immediate symptoms include throat inflammation and shortness of breath. After {@dice 1d6} hours, the infected character gains 1 level of {@condition exhaustion} that can''t be removed (except as described below) until the disease is cured. At the end of each long rest, the infected creature must repeat the saving throw. On a failed save, the creature''s {@condition exhaustion} increases by 1 level; on a successful save, the creature''s {@condition exhaustion} decreases by 1 level. If a successful saving throw reduces the infected creature''s level of {@condition exhaustion} below 1, the creature recovers from the disease."'::jsonb);
    INSERT INTO disease_entries (disease_id, entry_order, type, name, content, list_items, table_caption, table_col_labels, table_rows, raw_json) VALUES (disease_id_var, 1, NULL, NULL, 'Explorers can avoid contracting throat leeches by drinking only rainwater or water that''s been boiled or magically purified.', NULL::jsonb, NULL, NULL::jsonb, NULL::jsonb, '"Explorers can avoid contracting throat leeches by drinking only rainwater or water that''s been boiled or magically purified."'::jsonb);
END $DISEASE_INSERT_BLOCK$;

